apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: bahmni-ingress
  labels:
    environment: {{ .Values.metadata.labels.environment }}
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: {{ .Values.metadata.ingress.PROXY_BODY_SIZE }}
spec:
  ingressClassName: nginx
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          {{- if index .Values "bahmni-web" "enabled" }}
          - path: /
            pathType: Prefix
            backend:
              service:
                name: bahmni-web
                port:
                  number: 8091
          {{- end }}

          {{- if index .Values "bahmni-lab" "enabled" }}
          - path: /lab
            pathType: Prefix
            backend:
              service:
                name: bahmni-lab
                port:
                  number: 8090
          {{- end }}

          {{- if .Values.reports.enabled }}
          - path: /bahmnireports
            pathType: Prefix
            backend:
              service:
                name: reports
                port:
                  number: 8051
          {{- end }}

          {{- if index .Values "patient-documents" "enabled" }}
          - path: /document_images
            pathType: Prefix
            backend:
              service:
                name: patient-documents
                port:
                  number: 8099
          {{- end }}

          {{- if index .Values "patient-documents" "enabled" }}
          - path: /openmrs/auth
            pathType: Prefix
            backend:
              service:
                name: patient-documents
                port:
                  number: 8099
          {{- end }}

          {{- if index .Values "appointments" "enabled" }}
          - path: /appointments
            pathType: Prefix
            backend:
              service:
                name: appointments
                port:
                  number: 80
          {{- end }}

          {{- if index .Values "implementer-interface" "enabled" }}
          - path: /implementer-interface
            pathType: Prefix
            backend:
              service:
                name: implementer-interface
                port:
                  number: 80
          {{- end }}

    - host: payments-{{ .Values.ingress.host }}
      http:
        paths:
          {{- if .Values.crater.enabled }}
          - path: /
            pathType: Prefix
            backend:
              service:
                name: crater-nginx
                port:
                  number: 80
          {{- end }}
---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: openmrs-ingress
  labels:
    environment: {{ .Values.metadata.labels.environment }}
  annotations:
    nginx.ingress.kubernetes.io/configuration-snippet: |
      add_header Set-Cookie "reporting_session=$cookie_JSESSIONID;Path=/;Max-Age=86400";
    nginx.ingress.kubernetes.io/proxy-body-size: {{ .Values.metadata.ingress.PROXY_BODY_SIZE }}
spec:
  ingressClassName: nginx
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          {{- if index .Values "openmrs" "enabled" }}
          - path: /openmrs
            pathType: Prefix
            backend:
              service:
                name: openmrs
                port:
                  number: 8080
          {{- end }}
